name: Terragrunt Deploy
on:
  repository_dispatch:
    types: [trigger-deploy] # Triggered from infra-modules repo
  workflow_dispatch: # Manual trigger via GitHub UI
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    name: Deploy Terragrunt Infra
    runs-on: ubuntu-latest
    env:
      REPO_DISPATCH_PAT: ${{ secrets.REPO_DISPATCH_PAT }}
    defaults:
      run:
        shell: bash
        working-directory: Dev # Adjust this if you're deploying Prod or Staging
    
    steps:
      - name: Checkout Live Infra
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::649203810550:role/EksOIDCRole
          aws-region: eu-west-1
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      
      - name: Install Terragrunt
        run: |
          curl -L -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/
      
      - name: Format Check (Terragrunt)
        run: terragrunt hclfmt --terragrunt-check || true # not failing pipeline yet
      
      - name: Initialize Terragrunt Modules
        run: |
          # Initialize each module in dependency order
          (cd vpc && terragrunt init --upgrade)
          (cd eks && terragrunt init --upgrade)
          (cd kubernetes-addons && terragrunt init --upgrade)
      
      - name: Validate Terragrunt Modules
        run: terragrunt validate --all
      
      - name: Plan VPC
        run: |
          cd vpc
          terragrunt plan --non-interactive

      - name: Plan EKS
        run: |
          cd eks
          terragrunt plan --non-interactive

      - name: Plan Kubernetes Addons
        run: |
          cd kubernetes-addons
          terragrunt plan --non-interactive
        continue-on-error: true  


      - name: Apply VPC
        run: |
          cd vpc
          terragrunt apply --non-interactive --auto-approve

      - name: Apply EKS
        run: |
          cd eks
          terragrunt run-all apply --non-interactive --terragrunt-include-external-dependencies --auto-approve
          
      - name: Configure Kubeconfig
        run: |
            CLUSTER_NAME=$(terragrunt output -raw eks_name --working-dir=eks)
            REGION=$(terragrunt output -raw region --terragrunt-working-dir eks)
            aws eks update-kubeconfig --name $CLUSTER_NAME --region "${AWS_REGION}"


      - name: Apply Kubernetes Addons
        run: |
          cd kubernetes-addons
          terragrunt apply --non-interactive --auto-approve
          
            
        # - name: Terragrunt Apply
        #   run: terragrunt run-all apply --non-interactive --terragrunt-include-external-dependencies --auto-approve